import { test } from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync,readdirSync } from 'node:fs';
import ts from 'typescript';
const source=readFileSync(new URL('../lib/order-service.ts',import.meta.url),'utf8');
const js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
const {createOrder,changeOrder,setStock}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
function setup(stock=10){
 const sqlite=new DatabaseSync(':memory:');
 sqlite.exec('PRAGMA foreign_keys=ON');
 for(const file of readdirSync(new URL('../drizzle/',import.meta.url)).filter(n=>n.endsWith('.sql')).sort())sqlite.exec(readFileSync(new URL('../drizzle/'+file,import.meta.url),'utf8'));
 for(const [id,name,price,station] of [['donut','ドーナツ',250,'kitchen'],['cupcake','カップケーキ',250,'kitchen'],['churro','チュロス',250,'kitchen'],['float','綿あめフロート',200,'float'],['pack','パック',50,'pack']])sqlite.prepare('INSERT INTO products VALUES (?,?,?,?,?,0)').run(id,name,price,stock,station);
 const execute=(sql,args,kind)=>{const stmt=sqlite.prepare(sql);if(kind==='first')return stmt.get(...args)||null;if(kind==='all')return {results:stmt.all(...args)};return {meta:{changes:Number(stmt.run(...args).changes)}};};
 const db={prepare(sql){let args=[];return {sql,bind(...values){args=values;return this;},first(){return Promise.resolve(execute(sql,args,'first'));},all(){return Promise.resolve(execute(sql,args,'all'));},run(){return Promise.resolve(execute(sql,args,'run'));},execute(){return execute(sql,args,'run');}};},async batch(statements){sqlite.exec('BEGIN IMMEDIATE');try{const results=statements.map(s=>s.execute());sqlite.exec('COMMIT');return results;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
 const input=(extra={})=>({id:crypto.randomUUID(),usageType:'店内飲食',ticketType:'前売り券',customerNumber:1,items:[{productId:'donut',qty:2}],...extra});
 const count=()=>sqlite.prepare('SELECT COUNT(*) AS n FROM orders').get().n;
 const remaining=id=>sqlite.prepare('SELECT stock FROM products WHERE id=?').get(id).stock;
 return {db,input,count,remaining,sqlite};
}
test('order reserves stock, server price wins, retry is idempotent',async()=>{const x=setup();const order=x.input({total:1,items:[{productId:'donut',qty:2,price:1}]});await createOrder(x.db,'staff',order);await createOrder(x.db,'staff',order);assert.equal(x.count(),1);assert.equal(x.remaining('donut'),8);assert.equal(x.sqlite.prepare('SELECT SUM(price*qty) AS total FROM order_items').get().total,500);await assert.rejects(createOrder(x.db,'staff',{...order,customerNumber:2}),/異なる内容/);});
test('validation rejects negative, fractional, excessive, unknown and duplicate quantities',async()=>{const x=setup();for(const items of [[{productId:'donut',qty:-1}],[{productId:'donut',qty:1.5}],[{productId:'donut',qty:11}],[{productId:'invalid',qty:1}],[{productId:'donut',qty:1},{productId:'donut',qty:1}]])await assert.rejects(createOrder(x.db,'staff',x.input({items})));assert.equal(x.count(),0);assert.equal(x.remaining('donut'),10);});
test('takeout requires pack, seat ranges and pack-only orders enforced on server',async()=>{const x=setup();await assert.rejects(createOrder(x.db,'staff',x.input({usageType:'テイクアウト'})),/パック/);await assert.rejects(createOrder(x.db,'staff',x.input({usageType:'テイクアウト',customerNumber:9})),/範囲外/);await assert.rejects(createOrder(x.db,'staff',x.input({items:[{productId:'pack',qty:1}]})));await assert.rejects(createOrder(x.db,'staff',x.input({items:[{productId:'donut',qty:1},{productId:'pack',qty:1}]})),/店内/);await createOrder(x.db,'staff',x.input({usageType:'テイクアウト',customerNumber:8,items:[{productId:'donut',qty:1},{productId:'pack',qty:1}]}));assert.equal(x.remaining('pack'),9);});
test('two simultaneous orders for the last stock: one wins, loser rolls back all rows',async()=>{const x=setup(1);const result=await Promise.allSettled([createOrder(x.db,'a',x.input({items:[{productId:'donut',qty:1},{productId:'float',qty:1}]})),createOrder(x.db,'b',x.input({items:[{productId:'donut',qty:1},{productId:'float',qty:1}]}))]);assert.equal(result.filter(r=>r.status==='fulfilled').length,1);assert.equal(x.count(),1);assert.equal(x.remaining('donut'),0);assert.equal(x.remaining('float'),0);assert.equal(x.sqlite.prepare('SELECT COUNT(*) AS n FROM order_items').get().n,2);});
test('concurrent retry of identical request never reserves twice',async()=>{const x=setup();const input=x.input();await Promise.all([createOrder(x.db,'staff',input),createOrder(x.db,'staff',input)]);assert.equal(x.count(),1);assert.equal(x.remaining('donut'),8);});
test('cannot prepare or deliver before payment; both kitchen stations must complete',async()=>{const x=setup();const input=x.input({items:[{productId:'donut',qty:1},{productId:'float',qty:1}]});await createOrder(x.db,'staff',input);await assert.rejects(changeOrder(x.db,input.id,{action:'prepare',station:'kitchen'}));await assert.rejects(changeOrder(x.db,input.id,{action:'deliver'}));await changeOrder(x.db,input.id,{action:'pay'});await changeOrder(x.db,input.id,{action:'prepare',station:'kitchen'});await assert.rejects(changeOrder(x.db,input.id,{action:'deliver'}));await changeOrder(x.db,input.id,{action:'prepare',station:'float'});await changeOrder(x.db,input.id,{action:'deliver'});await changeOrder(x.db,input.id,{action:'deliver'});assert.equal(x.sqlite.prepare('SELECT status FROM orders').get().status,'delivered');});
test('concurrent cancellation returns inventory once and preserves history',async()=>{const x=setup();const input=x.input();await createOrder(x.db,'staff',input);await Promise.all([changeOrder(x.db,input.id,{action:'cancel',operationId:crypto.randomUUID()}),changeOrder(x.db,input.id,{action:'cancel',operationId:crypto.randomUUID()})]);assert.equal(x.remaining('donut'),10);assert.equal(x.count(),1);assert.equal(x.sqlite.prepare('SELECT status FROM orders').get().status,'cancelled');});
test('payment and cancellation race never restores stock for a paid order',async()=>{const x=setup();const input=x.input();await createOrder(x.db,'staff',input);await Promise.allSettled([changeOrder(x.db,input.id,{action:'pay'}),changeOrder(x.db,input.id,{action:'cancel',operationId:crypto.randomUUID()})]);const status=x.sqlite.prepare('SELECT status FROM orders').get().status;assert.ok(['paid','cancelled'].includes(status));assert.equal(x.remaining('donut'),status==='paid'?8:10);});
test('paid orders cannot be cancelled; stock edits reject stale values',async()=>{const x=setup();const input=x.input();await createOrder(x.db,'staff',input);await changeOrder(x.db,input.id,{action:'pay'});await assert.rejects(changeOrder(x.db,input.id,{action:'cancel',operationId:crypto.randomUUID()}),/未会計/);await assert.rejects(setStock(x.db,'donut',{stock:20,expectedStock:10}),/更新/);await setStock(x.db,'donut',{stock:20,expectedStock:8});assert.equal(x.remaining('donut'),20);await assert.rejects(setStock(x.db,'donut',{stock:-1,expectedStock:20}));});
